[package]
name = "cim"
version = "0.2.0"
description = "Keep an eye on your Gitlab pipelines"
authors = ["Dolugen Buuralda <dolugen@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "*"
tabular = "0.1.4"
