[package]
name = "cim"
version = "0.1.0"
authors = ["Dolugen Buuralda <dolugen@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
